name: TREASURE_HUNTER_ORACLE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      name: ${GITHUB_REPOSITORY#*/}"-dev"
      key: "ssh-key-scrap"
      stamp: ${GITHUB_SHA}
      host: ${{ vars.ORACLE_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          CHAINS: ${{ vars.CHAINS }}
          ORACLE_HOST: ${{ vars.ORACLE_HOST }}

          ADMIN_TG_ID: ${{ secrets.ADMIN_TG_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          ORACLE_SSH: ${{ secrets.ORACLE_SSH }}
        run: |
          echo "CHAINS=$CHAINS" >> .env
          echo "ADMIN_TG_ID=$ADMIN_TG_ID" >> .env
          echo "TG_BOT_TOKEN=$TG_BOT_TOKEN" >> .env
          echo "MONGO_URL=$MONGO_URL" >> .env
          echo "ORACLE_HOST=$ORACLE_HOST" >> .env
          echo "ORACLE_SSH=$ORACLE_SSH" >> .env
      - name: Enable buildx
        run: |
          sudo docker buildx create --use

      - name: Build docker
        run: |
          sudo docker buildx build -t ${{ env.name }}-${{ env.stamp }} --platform linux/amd64 --output type=docker .
      #  --platform linux/amd64,linux/arm64,linux/arm/v8

      - name: Show images
        run: |
          sudo docker images

      - name: Save image
        run: |
          docker save -o ${{ env.name }}-${{ env.stamp }}.tar ${{ env.name }}-${{ env.stamp }}

      - name: Save secret key
        run: |
          echo "${{ secrets.ORACLE_SSH }}" > ${key}
          sudo chmod 600 ${key}

      - name: Copy image
        run: |
          scp -i ${key} -o "StrictHostKeyChecking no" ${{ env.name }}-${{ env.stamp }}.tar ${{ env.host }}:${{ env.name }}-${{ env.stamp }}.tar

      - name: Start image
        run: |
          ssh -i ${key} -o "StrictHostKeyChecking no" ${{ env.host }} 'sudo docker load -i '${{ env.name }}'-'${{ env.stamp }}'.tar; \
          sudo docker stop '${{ env.name }}' || true; \
          sudo docker run --log-driver json-file --log-opt max-size=10m --log-opt max-file=1 -d --restart always -p 3033:3033 --name '${{ env.name }}'-new '${{ env.name }}'-'${{ env.stamp }}'; \
          sudo docker rm '${{ env.name }}' || true; sudo docker rmi $(sudo docker images -q) || true; \
          sudo docker rename '${{ env.name }}'-new '${{ env.name }}'; rm '${{ env.name }}'-'${{ env.stamp }}'.tar'
